# Generated by Django 2.1.6 on 2019-02-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='has_answer',
            field=models.BooleanField(default=False),
        ),
    ]
