# Generated by Django 2.1.6 on 2019-02-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190212_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='has_answer',
            new_name='closed',
        ),
    ]
